# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='foto_profil',
            field=models.ImageField(blank=True, upload_to='foto_profil_administrator'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='jenis_kelamin',
            field=models.CharField(choices=[('pria', 'Pria'), ('wanita', 'Wanita')], default='pria', max_length=10),
        ),
        migrations.AlterField(
            model_name='berita',
            name='foto_berita',
            field=models.ImageField(blank=True, upload_to='foto_berita'),
        ),
    ]
