# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-14 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FotoReview',
            fields=[
                ('id_foto_profil', models.AutoField(primary_key=True, serialize=False)),
                ('foto_review', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Pengunjung',
            fields=[
                ('nama', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tempat_tanggal_lahir', models.DateField()),
                ('golongan_darah', models.CharField(max_length=3)),
                ('alamat', models.TextField()),
                ('jenis_kelamin', models.CharField(max_length=8)),
                ('nomor_telepon', models.CharField(max_length=20)),
                ('foto_profil', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id_review', models.AutoField(primary_key=True, serialize=False)),
                ('isi_review', models.TextField()),
                ('waktu_stamp', models.DateTimeField(auto_now_add=True)),
                ('waktu_validasi', models.DateTimeField(blank=True)),
                ('data_lokasi_user', models.CharField(max_length=300)),
                ('status_validasi', models.CharField(choices=[('rejected', 'Rejected'), ('validated', 'Validated'), ('request', 'Request'), ('rejected_by_system', 'Rejected By System')], default='request', max_length=50)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
