# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-14 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengunjung', '0002_auto_20170514_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengunjung',
            name='jenis_kelamin',
            field=models.CharField(choices=[('pria', 'Pria'), ('wanita', 'Wanita')], default='pria', max_length=8),
        ),
    ]
