# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-14 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengunjung', '0004_auto_20170514_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='data_lokasi_x',
            new_name='data_lokasi_user',
        ),
    ]
