# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-14 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengunjung', '0005_auto_20170514_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='data_lokasi_user',
            new_name='data_lokasi_pengunjung',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='pengunjung',
        ),
    ]
