# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengunjung', '0006_auto_20170515_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoreview',
            name='foto_review',
            field=models.ImageField(blank=True, upload_to='foto_review'),
        ),
        migrations.AlterField(
            model_name='pengunjung',
            name='foto_profil',
            field=models.ImageField(blank=True, upload_to='foto_profil_pengunjung'),
        ),
    ]
