# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengunjung', '0007_auto_20170515_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengunjung',
            name='tanggal_lahir',
            field=models.DateField(default='dsds'),
        ),
        migrations.AlterField(
            model_name='pengunjung',
            name='tempat_tanggal_lahir',
            field=models.CharField(default='dattk', max_length=50),
        ),
    ]
