# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengunjung', '0008_auto_20170515_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengunjung',
            name='tanggal_lahir',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pengunjung',
            name='tempat_tanggal_lahir',
            field=models.CharField(max_length=50),
        ),
    ]
