# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengunjung', '0010_remove_pengunjung_tempat_tanggal_lahir'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengunjung',
            name='tempat_tanggal_lahir',
            field=models.CharField(default='ganteng', max_length=50),
        ),
    ]
