# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengunjung', '0013_auto_20170515_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengunjung',
            name='tanggal_lahir',
            field=models.DateField(),
        ),
    ]
