# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-14 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rumah_sakit', '0001_initial'),
        ('utama', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asuransi',
            fields=[
                ('nama', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('url_website', models.CharField(max_length=400, unique=True)),
                ('dokumen', models.FileField(blank=True, upload_to='')),
                ('foto_profil', models.ImageField(blank=True, upload_to='')),
                ('nomor_telepon', models.CharField(max_length=20)),
                ('status_validasi', models.CharField(choices=[('rejected', 'Rejected'), ('validated', 'Validated'), ('request', 'Request')], default='request', max_length=50)),
                ('waktu_validasi', models.DateTimeField(blank=True)),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utama.Administrator')),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utama.Akun')),
            ],
        ),
        migrations.CreateModel(
            name='HubunganRumahSakitAsuransi',
            fields=[
                ('id_hubungan_rumah_sakit_asuransi', models.AutoField(primary_key=True, serialize=False)),
                ('dokumen', models.FileField(blank=True, upload_to='')),
                ('status_validasi_rumah_sakit', models.CharField(choices=[('rejected', 'Rejected'), ('validated', 'Validated'), ('request', 'Request')], default='request', max_length=50)),
                ('status_validasi_administrator', models.CharField(choices=[('rejected', 'Rejected'), ('validated', 'Validated'), ('request', 'Request')], default='request', max_length=50)),
                ('waktu_validasi', models.DateTimeField(blank=True)),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utama.Administrator')),
                ('asuransi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asuransi.Asuransi')),
                ('rumah_sakit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rumah_sakit.RumahSakit')),
            ],
        ),
    ]
