# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumah_sakit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotorumahsakit',
            name='foto_rumah_sakit',
            field=models.ImageField(blank=True, upload_to='foto_rumah_sakit'),
        ),
        migrations.AlterField(
            model_name='rumahsakit',
            name='dokumen',
            field=models.FileField(blank=True, upload_to='dokumen_rumah_sakit'),
        ),
        migrations.AlterField(
            model_name='rumahsakit',
            name='foto_profil',
            field=models.ImageField(blank=True, upload_to='foto_profil_rumah_sakit'),
        ),
    ]
